// Code generated by MockGen. DO NOT EDIT.
// Source: ./utils/auth_middleware.go

// Package mockutl is a generated GoMock package.
package mockutl

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAuthMiddleware is a mock of AuthMiddleware interface.
type MockAuthMiddleware struct {
	ctrl     *gomock.Controller
	recorder *MockAuthMiddlewareMockRecorder
}

// MockAuthMiddlewareMockRecorder is the mock recorder for MockAuthMiddleware.
type MockAuthMiddlewareMockRecorder struct {
	mock *MockAuthMiddleware
}

// NewMockAuthMiddleware creates a new mock instance.
func NewMockAuthMiddleware(ctrl *gomock.Controller) *MockAuthMiddleware {
	mock := &MockAuthMiddleware{ctrl: ctrl}
	mock.recorder = &MockAuthMiddlewareMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthMiddleware) EXPECT() *MockAuthMiddlewareMockRecorder {
	return m.recorder
}

// CheckIsAuthenticated mocks base method.
func (m *MockAuthMiddleware) CheckIsAuthenticated(handler func(http.ResponseWriter, *http.Request)) http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckIsAuthenticated", handler)
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// CheckIsAuthenticated indicates an expected call of CheckIsAuthenticated.
func (mr *MockAuthMiddlewareMockRecorder) CheckIsAuthenticated(handler interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckIsAuthenticated", reflect.TypeOf((*MockAuthMiddleware)(nil).CheckIsAuthenticated), handler)
}
