// Code generated by MockGen. DO NOT EDIT.
// Source: ./utils/token.go

// Package mockutl is a generated GoMock package.
package mockutl

import (
	reflect "reflect"

	utils "github.com/gadhittana01/go-modules/utils"
	gomock "github.com/golang/mock/gomock"
)

// MockTokenClient is a mock of TokenClient interface.
type MockTokenClient struct {
	ctrl     *gomock.Controller
	recorder *MockTokenClientMockRecorder
}

// MockTokenClientMockRecorder is the mock recorder for MockTokenClient.
type MockTokenClientMockRecorder struct {
	mock *MockTokenClient
}

// NewMockTokenClient creates a new mock instance.
func NewMockTokenClient(ctrl *gomock.Controller) *MockTokenClient {
	mock := &MockTokenClient{ctrl: ctrl}
	mock.recorder = &MockTokenClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenClient) EXPECT() *MockTokenClientMockRecorder {
	return m.recorder
}

// DecodeToken mocks base method.
func (m *MockTokenClient) DecodeToken(req utils.DecodeTokenReq) (utils.DecodeTokenRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecodeToken", req)
	ret0, _ := ret[0].(utils.DecodeTokenRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecodeToken indicates an expected call of DecodeToken.
func (mr *MockTokenClientMockRecorder) DecodeToken(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecodeToken", reflect.TypeOf((*MockTokenClient)(nil).DecodeToken), req)
}

// GenerateToken mocks base method.
func (m *MockTokenClient) GenerateToken(req utils.GenerateTokenReq) (utils.GenerateTokenResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateToken", req)
	ret0, _ := ret[0].(utils.GenerateTokenResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateToken indicates an expected call of GenerateToken.
func (mr *MockTokenClientMockRecorder) GenerateToken(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateToken", reflect.TypeOf((*MockTokenClient)(nil).GenerateToken), req)
}
